# Generated by Django 2.2.1 on 2019-06-27 03:14

import apps.adminview.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0001_initial'),
    ]

    operations = [
        
    ]
