# Generated by Django 2.2.1 on 2019-06-28 03:46

import apps.adminview.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0002_auto_20190626_2244'),
    ]

    operations = [
        
    ]
