# Generated by Django 2.1.4 on 2019-07-01 18:29

import apps.adminview.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0004_available_design_page_contactdata_enterprisedata_politics_teammembers_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_design_page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('type_design', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('isSelected', models.BooleanField(default=False)),
                ('temp_selected', models.BooleanField(default=False)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('image_path', models.ImageField(height_field='height_field', upload_to='', width_field='width_field')),
                ('image_path1', models.ImageField(height_field='height_field', upload_to='', width_field='width_field')),
                ('image_path2', models.ImageField(height_field='height_field', upload_to='', width_field='width_field')),
            ],
        ),
        migrations.CreateModel(
            name='contactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.TextField(blank=True, null=True)),
                ('horario', models.TextField(blank=True, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('image_path', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.adminview.models.upload_location, width_field='width_field')),
                ('googleMaps', models.TextField(blank=True, null=True)),
                ('mapActivated', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='enterprisedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('employees', models.IntegerField(default=0)),
                ('name', models.TextField(blank=True, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('direction', models.TextField(null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('image_path', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.adminview.models.upload_location, width_field='width_field')),
                ('copyright', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='indexDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('carrousel1', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.adminview.models.upload_location, width_field='width_field')),
                ('carrousel2', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.adminview.models.upload_location, width_field='width_field')),
                ('carrousel3', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.adminview.models.upload_location, width_field='width_field')),
                ('carrousel4', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.adminview.models.upload_location, width_field='width_field')),
                ('title', models.TextField(blank=True, null=True)),
                ('portada', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.adminview.models.upload_location, width_field='width_field')),
            ],
        ),
        migrations.CreateModel(
            name='teamMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('image_path', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.adminview.models.upload_location, width_field='width_field')),
                ('existencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('template_name', models.TextField(blank=True, null=True)),
                ('isSelected', models.BooleanField(default=False)),
                ('temp_selected', models.BooleanField(default=False)),
                ('width_field', models.IntegerField(default=0, null=True)),
                ('height_field', models.IntegerField(default=0, null=True)),
                ('image_path', models.ImageField(height_field='height_field', upload_to='', width_field='width_field')),
            ],
        ),
    ]
