# Generated by Django 2.1.4 on 2019-07-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0005_available_design_page_contactdata_enterprisedata_indexdesign_teammembers_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprisedata',
            old_name='image_path',
            new_name='logo',
        ),
        migrations.AlterField(
            model_name='contactdata',
            name='mapActivated',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
