# Generated by Django 2.1.4 on 2020-03-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminview', '0006_auto_20190701_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisedata',
            name='direction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisedata',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
