# Generated by Django 2.1.4 on 2019-06-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_factura_id_usuario_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura_det',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='factura',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_codigo_retiro',
            field=models.CharField(blank=True, default='abc', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='factura_det',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
