# Generated by Django 2.1.4 on 2019-06-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_auto_20190625_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_codigo_retiro',
            field=models.CharField(blank=True, default='abc', editable=False, max_length=120, null=True),
        ),
    ]
