# Generated by Django 2.1.4 on 2019-06-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_auto_20190625_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_codigo_retiro',
            field=models.CharField(blank=True, default='abc', max_length=120, null=True),
        ),
    ]
