# Generated by Django 2.1.4 on 2019-06-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_auto_20190625_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_codigo_retiro',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
