# Generated by Django 2.1.4 on 2019-07-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_auto_20190625_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_credit_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('cvc', models.CharField(max_length=3)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
    ]
