# Generated by Django 2.1.4 on 2019-07-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_user_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura_det',
            name='id_articulo_fk',
        ),
        migrations.RemoveField(
            model_name='factura_det',
            name='id_factura_fk',
        ),
        migrations.DeleteModel(
            name='Factura_det',
        ),
    ]
