# Generated by Django 2.1.4 on 2019-07-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190701_1700'),
        ('factura', '0009_auto_20190704_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True)),
                ('valoracion', models.IntegerField(blank=True, default=0, null=True)),
                ('id_factura_fk', models.ForeignKey(db_column='id_factura_fk', on_delete=django.db.models.deletion.CASCADE, to='factura.Factura')),
                ('id_productos_fk', models.ForeignKey(db_column='id_productos_fk', on_delete=django.db.models.deletion.CASCADE, to='article.Articulo')),
            ],
        ),
    ]
