# Generated by Django 2.1.4 on 2019-07-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0010_factura_det'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura_det',
            old_name='cantidad',
            new_name='quantity',
        ),
    ]
