# Generated by Django 2.1.4 on 2019-07-04 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0012_factura_det_price_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura_det',
            name='id_productos_fk',
            field=models.ForeignKey(blank=True, db_column='id_productos_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Articulo'),
        ),
    ]
