# Generated by Django 2.1.4 on 2019-07-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0013_auto_20190704_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
