# Generated by Django 2.1.4 on 2019-07-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0014_factura_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='valorado',
            field=models.BooleanField(default=False),
        ),
    ]
