# Generated by Django 2.1.4 on 2019-07-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0015_factura_valorado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='factura',
            old_name='Entregado',
            new_name='entregado',
        ),
    ]
