# Generated by Django 2.1.4 on 2019-07-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0017_auto_20190705_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='fecha_entregado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
