# Generated by Django 2.1.4 on 2019-07-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0018_factura_fecha_entregado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_entregado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
