# Generated by Django 2.1.4 on 2019-05-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carro_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('precio_venta', models.FloatField(default=0)),
                ('total', models.FloatField(default=0)),
                ('id_articulo_fk', models.ForeignKey(db_column='id_articulo_fk', on_delete=django.db.models.deletion.CASCADE, to='article.Articulo')),
                ('id_carro_fk', models.ForeignKey(blank=True, db_column='id_carro_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.Carro')),
            ],
        ),
    ]
