# Generated by Django 2.1.4 on 2019-06-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_carro_id_usuario_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro_det',
            name='id_articulo_fk',
        ),
        migrations.RemoveField(
            model_name='carro_det',
            name='id_carro_fk',
        ),
        migrations.DeleteModel(
            name='Carro_det',
        ),
    ]
