# Generated by Django 2.1.4 on 2019-06-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20190618_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
