# Generated by Django 2.1.4 on 2019-06-18 15:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_clasificacion_descripcion'),
        ('cart', '0005_carro_cantidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carro',
            new_name='Cart',
        ),
    ]
