# Generated by Django 2.1.4 on 2019-06-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20190618_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=100, null=True),
        ),
    ]
