# Generated by Django 2.1.4 on 2019-06-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='id_productos_fk',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='id_usuario_fk',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='id_productos_fk',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
