# Generated by Django 2.1.4 on 2019-06-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_auto_20190530_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('Corriente', 'Corriente'), ('Moderador', 'Moderador'), ('Administrador', 'Administrador')], default='Corriente', max_length=500),
        ),
    ]
