# Generated by Django 2.2.1 on 2019-06-30 18:57

import apps.myuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0003_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.myuser.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
