# Generated by Django 2.1.4 on 2019-07-01 21:13

import apps.myuser.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0004_auto_20190630_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_field', models.IntegerField(default=0)),
                ('height_field', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.myuser.models.upload_location, width_field='width_field')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ForeignKey(blank=True, db_column='id_Photo_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='myuser.Photo'),
        ),
    ]
