# Generated by Django 2.1.4 on 2019-07-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0005_auto_20190701_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=10000.0, max_digits=100, null=True),
        ),
    ]
