# Generated by Django 2.1.4 on 2019-07-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0006_customuser_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
