# Generated by Django 2.1.4 on 2019-07-04 15:50

import apps.myuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0008_auto_20190702_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='photo_f',
        ),
        migrations.AddField(
            model_name='customuser',
            name='height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.myuser.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='width_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
