# Generated by Django 2.1.4 on 2019-05-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=64)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('long_descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.FloatField()),
                ('cantidad', models.IntegerField()),
                ('existencia', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='')),
                ('valoracion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clasificacion', models.CharField(max_length=64)),
                ('existencia', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='id_clasificacion_fk',
            field=models.ForeignKey(blank=True, db_column='id_clasificacion_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Clasificacion'),
        ),
    ]
