# Generated by Django 2.1.4 on 2019-05-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='imagen',
            new_name='nombre_imagen',
        ),
    ]
