# Generated by Django 2.1.4 on 2019-05-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190527_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articulo',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
