# Generated by Django 2.1.4 on 2019-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20190527_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
