# Generated by Django 2.2.1 on 2019-06-11 23:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20190527_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='clasificacion',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
