# Generated by Django 2.1.4 on 2019-07-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_clasificacion_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
