# Generated by Django 2.1.4 on 2019-07-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190701_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='agotado',
            field=models.BooleanField(default=False),
        ),
    ]
