# Generated by Django 2.1.4 on 2019-07-06 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_articulo_agotado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Tiene ser mayor a 0')]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Tiene ser mayor a 0')]),
        ),
    ]
