# Generated by Django 2.2.1 on 2019-07-08 15:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_auto_20190706_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Tiene que ser mayor a 0')]),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Tiene que ser mayor a 0')]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(blank=True, null=True)),
                ('asunto', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('existencia', models.BooleanField(default=True)),
                ('id_article_fk', models.ForeignKey(blank=True, db_column='id_article_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to='article.Articulo')),
                ('id_user_fk', models.ForeignKey(blank=True, db_column='id_user_fk', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
